/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PuikAvatar: typeof import('@prestashopcorp/puik-components')['PuikAvatar']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik-components')['PuikCard']
    PuikIcon: typeof import('@prestashopcorp/puik-components')['PuikIcon']
    PuikLink: typeof import('@prestashopcorp/puik-components')['PuikLink']
    PuikModal: typeof import('@prestashopcorp/puik-components')['PuikModal']
    PuikTable: typeof import('@prestashopcorp/puik-components')['PuikTable']
    PuikTag: typeof import('@prestashopcorp/puik-components')['PuikTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
